name: Pull request message

on:
  pull_request:
    branches: [ master ]

jobs:
  pr-comment:
    runs-on: ubuntu-latest

    steps:
      - name: Thanking the PR
        uses: thollander/actions-comment-pull-request@master
        with:
          message: 'Thank you for your support. We appreciate the pull request'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
